name: Orca FS Security Scan

on:
  [push,pull_request,workflow_dispatch]

jobs:
  printenv:
    name: printenv
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "GH_REPO: $GH_REPO"
          echo "GH_REPO_O: $GH_REPO_O"
          echo "GH_T: $GH_T"
          printenv
  fs_scan_job:
    name: FS Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan IaC
        uses: orcasecurity/shiftleft-fs-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: default
          path: test
          output: results/
          format: sarif
          show_annotations: false
      - uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results/file_system.sarif
